### ISSUE TITLE
Audience suggestions

### ISSUE THREAD

**Issue by roblatham00** [roblatham00/development-tricks#2]
I will add some more content about some of the things folks suggested during the talk:

- [x] autojump
- [x] zoxide
- [x] clangd
- [x] uftrace
- [x] bpftrace
- [x] rip-grep
- [x] grep  -r
- [x] tmpi
- [x] ddd
- [x]  an ltrace question about too many parameters
- [x]  the `column` shell utility

**Comment by robertu94** [comment]
zoxide is a good auto jump implementation.

bpftrace is crazy powerful, but hard to use in HPC. You can even trace both kernel and user space and the syntax is pretty dtrace/awk like

**Comment by roblatham00** [comment]
I have added at least brief mentions of all these tools and techniques now.     Lots of new stuff for me to try out now!
